#include "global.h"

int SAMPLESIZE = 100000;
int EQUIDISTANT_SAMPLESIZE = 10000;
int DEFAULT_BASE_VARIANCE = 1;
int MAX_NUMBER_OF_STATES = 5;
double DEFAULT_VAR = 9;
double DEFAULT_MU = .5;
int EQUIDISTANT_PASS = 10;
int LOWER_BOUND = 0;
int UPPER_BOUND = 1;
int EVIDENCE_STATE_1 = 0;
int EVIDENCE_STATE_2 = 1;
int EVIDENCE_STATE_3 = 2;
int EVIDENCE_STATE_4 = 3;
int EVIDENCE_STATE_5 = 4;